openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://127.0.0.1:8080/api/v1"
  - url: "http://localhost:8080/api/v1"
paths:
  /printers:
    get:
      summary: Lists all available printers
      description: Retrieves a list of all printers configured on the system using the lpstat -p command.
      tags:
        - Printers
      responses:
        '200':
          description: List of available printers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: The name of the printer.
                    description:
                      type: string
                      description: Long description
                  required:
                    - name
                    - description
        '500':
          description: Failed to retrieve printer list
          content:
            text/plain:
              schema:
                type: string
                description: Error details from lpstat command or execution failure.
                example: "Error executing lpstat command: Permission denied"

  /print-job:
    post:
      summary: Uploads and prints a file
      description: Uploads a file and sends it to the specified printer using the lp command.
      tags:
        - Print Jobs
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - printer_name
                - file
              properties:
                printer_name:
                  type: string
                  description: Name of the printer to send the print job to (alphanumeric, underscores, hyphens, max 128 characters).
                  example: MyPrinter
                  pattern: ^[a-zA-Z0-9_-]{1,128}$
                file:
                  type: string
                  format: binary
                  description: File to print.
                copies:
                  type: integer
                  description: Number of copies to print (optional).
                  minimum: 1
                  default: 1
                  example: 2
                options:
                  type: array
                  description: Additional printer options (optional).
                  items:
                    type: string
                  example: [
                    "sides=two-sided-long-edge",
                    "media=A4",
                    "ColorModel=Gray",
                    "ColorModel=Monochrome",
                    "cupsPrintQuality=Draft", # "Normal", "High"
                    "print-quality=3", # "Draft"
                    "print-quality=4" # "Normal"
                  ]
      responses:
        '200':
          description: Print job sent successfully
          content:
            text/plain:
              schema:
                type: string
                description: Output from the lp command or success message.
                example: request id is MyPrinter-123 (1 file)
        '400':
          description: Invalid input
          content:
            text/plain:
              schema:
                type: string
                description: Error message indicating invalid or missing parameters or file type.
                example: Invalid file type
        '500':
          description: Failed to process print job
          content:
            text/plain:
              schema:
                type: string
                description: Error details from lp command or file processing.
                example: "Error executing lp command: Printer not found"

components:
  schemas: { }